language: node_js
cache: yarn
notifications:
  email: false
env:
  global:
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
  - COMMIT_AUTHOR_NAME: Travis CI
  - SOURCE_BRANCH: master
before_script:
after_success:
  - bash ./deploy/publish_to_npm.sh
